/**
* MOTC Transport  API V2
* </div>   <div class=\"info_description markdown\">本平臺提供涵蓋全國尺度之公車、臺鐵、高鐵、捷運、航空、自行車等公共運輸旅運資料服務API，歡迎各產政學單位介接使用。<br><span class=\"swagger-description-indicatation\">利用本平臺開放資料進行各項應用服務開發時，請考量不同特性使用者(如:性別/殘障/視障/老幼等)的需求，並歡迎回饋寶貴意見。</span><br><br>資料使用葵花寶典:<a href= https://ptxmotc.gitbooks.io/ptx-api-documentation/content/ >請點我</a><br>資料服務開發實作參考手冊:<a href= https://docs.google.com/viewer?url=https://github.com/ptxmotc/PTX_Web/blob/master/Swagger%E6%9C%8D%E5%8B%99%E8%AA%AA%E6%98%8E%E4%B8%8A%E5%82%B3%E5%8F%83%E8%80%83%E6%AA%94%E6%A1%88/%E5%85%AC%E5%85%B1%E9%81%8B%E8%BC%B8%E6%95%B4%E5%90%88%E8%B3%87%E8%A8%8A%E5%B9%B3%E5%8F%B0%E8%B3%87%E6%96%99%E6%9C%8D%E5%8B%99%E9%96%8B%E7%99%BC%E5%AF%A6%E4%BD%9C.pdf?raw=true >請點我</a><br>API URI Convention文件說明:<a href= https://docs.google.com/viewer?url=https://github.com/ptxmotc/PTX_Web/blob/master/Swagger%E6%9C%8D%E5%8B%99%E8%AA%AA%E6%98%8E%E4%B8%8A%E5%82%B3%E5%8F%83%E8%80%83%E6%AA%94%E6%A1%88/API_URI_Convention%E6%96%87%E4%BB%B6_v1.pdf?raw=true >請點我</a>
*
* OpenAPI spec version: v2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.apis

import org.openapitools.client.models.ServiceDTOVersion2BikeBikeAvailability
import org.openapitools.client.models.ServiceDTOVersion2BikeBikeStation

import org.openapitools.client.infrastructure.*

class BikeApiApi(basePath: kotlin.String = "http://ptx.transportdata.tw/MOTC") : ApiClient(basePath) {

    /**
    * 取得動態指定[縣市]的公共自行車即時車位資料
    * 取得動態指定[縣市]的公共自行車即時車位資料&lt;br /&gt;[更新頻率]2分鐘更新一次
    * @param city 欲查詢縣市 
    * @param &#x60;$format&#x60; 指定來源格式 
    * @param &#x60;$select&#x60; 挑選 (optional, default to null)
    * @param &#x60;$filter&#x60; 過濾 (optional, default to null)
    * @param &#x60;$orderby&#x60; 排序 (optional, default to null)
    * @param &#x60;$top&#x60; 取前幾筆 (optional, default to 30)
    * @param &#x60;$skip&#x60; 跳過前幾筆 (optional, default to null)
    * @return kotlin.Array<ServiceDTOVersion2BikeBikeAvailability>
    */
    @Suppress("UNCHECKED_CAST")
    fun bikeApiAvailability(city: kotlin.String, &#x60;$format&#x60;: kotlin.String, &#x60;$select&#x60;: kotlin.String? = null, &#x60;$filter&#x60;: kotlin.String? = null, &#x60;$orderby&#x60;: kotlin.String? = null, &#x60;$top&#x60;: kotlin.String? = null, &#x60;$skip&#x60;: kotlin.String? = null) : kotlin.Array<ServiceDTOVersion2BikeBikeAvailability> {
        val localVariableBody: kotlin.Any? = null
        val localVariableQuery: Map<String, List<String>?> = mapOf("$select" to if (&#x60;$select&#x60; != null) listOf("$&#x60;$select&#x60;") else null, "$filter" to if (&#x60;$filter&#x60; != null) listOf("$&#x60;$filter&#x60;") else null, "$orderby" to if (&#x60;$orderby&#x60; != null) listOf("$&#x60;$orderby&#x60;") else null, "$top" to if (&#x60;$top&#x60; != null) listOf("$&#x60;$top&#x60;") else null, "$skip" to if (&#x60;$skip&#x60; != null) listOf("$&#x60;$skip&#x60;") else null, "$format" to if (&#x60;$format&#x60; != null) listOf("$&#x60;$format&#x60;") else null)
        val localVariableHeaders: kotlin.collections.Map<kotlin.String,kotlin.String> = mapOf()
        val localVariableConfig = RequestConfig(
            RequestMethod.GET,
            "/v2/Bike/Availability/{City}".replace("{"+"City"+"}", "$city"),
            query = localVariableQuery,
            headers = localVariableHeaders
        )
        val response = request<kotlin.Array<ServiceDTOVersion2BikeBikeAvailability>>(
            localVariableConfig,
            localVariableBody
        )

        return when (response.responseType) {
            ResponseType.Success -> (response as Success<*>).data as kotlin.Array<ServiceDTOVersion2BikeBikeAvailability>
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).statusCode, (response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).statusCode, (response as ServerError<*>).message ?: "Server error")
            else -> throw kotlin.IllegalStateException("Undefined ResponseType.")
        }
    }

    /**
    * 取得指定[縣市]的公共自行車租借站位資料
    * 取得指定[縣市]的公共自行車租借站位資料&lt;br /&gt;[更新頻率]2分鐘更新一次
    * @param city 欲查詢縣市 
    * @param &#x60;$format&#x60; 指定來源格式 
    * @param &#x60;$select&#x60; 挑選 (optional, default to null)
    * @param &#x60;$filter&#x60; 過濾 (optional, default to null)
    * @param &#x60;$orderby&#x60; 排序 (optional, default to null)
    * @param &#x60;$top&#x60; 取前幾筆 (optional, default to 30)
    * @param &#x60;$skip&#x60; 跳過前幾筆 (optional, default to null)
    * @param &#x60;$spatialFilter&#x60; 空間過濾 (optional, default to null)
    * @return kotlin.Array<ServiceDTOVersion2BikeBikeStation>
    */
    @Suppress("UNCHECKED_CAST")
    fun bikeApiStation(city: kotlin.String, &#x60;$format&#x60;: kotlin.String, &#x60;$select&#x60;: kotlin.String? = null, &#x60;$filter&#x60;: kotlin.String? = null, &#x60;$orderby&#x60;: kotlin.String? = null, &#x60;$top&#x60;: kotlin.String? = null, &#x60;$skip&#x60;: kotlin.String? = null, &#x60;$spatialFilter&#x60;: kotlin.String? = null) : kotlin.Array<ServiceDTOVersion2BikeBikeStation> {
        val localVariableBody: kotlin.Any? = null
        val localVariableQuery: Map<String, List<String>?> = mapOf("$select" to if (&#x60;$select&#x60; != null) listOf("$&#x60;$select&#x60;") else null, "$filter" to if (&#x60;$filter&#x60; != null) listOf("$&#x60;$filter&#x60;") else null, "$orderby" to if (&#x60;$orderby&#x60; != null) listOf("$&#x60;$orderby&#x60;") else null, "$top" to if (&#x60;$top&#x60; != null) listOf("$&#x60;$top&#x60;") else null, "$skip" to if (&#x60;$skip&#x60; != null) listOf("$&#x60;$skip&#x60;") else null, "$spatialFilter" to if (&#x60;$spatialFilter&#x60; != null) listOf("$&#x60;$spatialFilter&#x60;") else null, "$format" to if (&#x60;$format&#x60; != null) listOf("$&#x60;$format&#x60;") else null)
        val localVariableHeaders: kotlin.collections.Map<kotlin.String,kotlin.String> = mapOf()
        val localVariableConfig = RequestConfig(
            RequestMethod.GET,
            "/v2/Bike/Station/{City}".replace("{"+"City"+"}", "$city"),
            query = localVariableQuery,
            headers = localVariableHeaders
        )
        val response = request<kotlin.Array<ServiceDTOVersion2BikeBikeStation>>(
            localVariableConfig,
            localVariableBody
        )

        return when (response.responseType) {
            ResponseType.Success -> (response as Success<*>).data as kotlin.Array<ServiceDTOVersion2BikeBikeStation>
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).statusCode, (response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).statusCode, (response as ServerError<*>).message ?: "Server error")
            else -> throw kotlin.IllegalStateException("Undefined ResponseType.")
        }
    }

}
