/**
* MOTC Transport  API V2
* </div>   <div class=\"info_description markdown\">本平臺提供涵蓋全國尺度之公車、臺鐵、高鐵、捷運、航空、自行車等公共運輸旅運資料服務API，歡迎各產政學單位介接使用。<br><span class=\"swagger-description-indicatation\">利用本平臺開放資料進行各項應用服務開發時，請考量不同特性使用者(如:性別/殘障/視障/老幼等)的需求，並歡迎回饋寶貴意見。</span><br><br>資料使用葵花寶典:<a href= https://ptxmotc.gitbooks.io/ptx-api-documentation/content/ >請點我</a><br>資料服務開發實作參考手冊:<a href= https://docs.google.com/viewer?url=https://github.com/ptxmotc/PTX_Web/blob/master/Swagger%E6%9C%8D%E5%8B%99%E8%AA%AA%E6%98%8E%E4%B8%8A%E5%82%B3%E5%8F%83%E8%80%83%E6%AA%94%E6%A1%88/%E5%85%AC%E5%85%B1%E9%81%8B%E8%BC%B8%E6%95%B4%E5%90%88%E8%B3%87%E8%A8%8A%E5%B9%B3%E5%8F%B0%E8%B3%87%E6%96%99%E6%9C%8D%E5%8B%99%E9%96%8B%E7%99%BC%E5%AF%A6%E4%BD%9C.pdf?raw=true >請點我</a><br>API URI Convention文件說明:<a href= https://docs.google.com/viewer?url=https://github.com/ptxmotc/PTX_Web/blob/master/Swagger%E6%9C%8D%E5%8B%99%E8%AA%AA%E6%98%8E%E4%B8%8A%E5%82%B3%E5%8F%83%E8%80%83%E6%AA%94%E6%A1%88/API_URI_Convention%E6%96%87%E4%BB%B6_v1.pdf?raw=true >請點我</a>
*
* OpenAPI spec version: v2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json
/**
 * 業管機關資料型別
 * @param newsID 最新消息原單位發布代碼
 * @param language 語系
 * @param department 發布單位
 * @param title 消息標題
 * @param newsCategory 消息類別
 * @param description 內容描述
 * @param newsURL 報導網站連結
 * @param attachmentURL 相關網站連結
 * @param publishTime 消息公告日期時間
 * @param startTime 開始時間
 * @param endTime 結束時間
 * @param updateTime 消息更新時間
 */
data class ServiceDTOVersion2BaseNews (
    /* 最新消息原單位發布代碼 */
    val newsID: java.util.UUID,
    /* 語系 */
    val language: kotlin.String,
    /* 內容描述 */
    val description: kotlin.String,
    /* 發布單位 */
    val department: kotlin.String? = null,
    /* 消息標題 */
    val title: kotlin.String? = null,
    /* 消息類別 */
    val newsCategory: ServiceDTOVersion2BaseNews.NewsCategory? = null,
    /* 報導網站連結 */
    val newsURL: kotlin.String? = null,
    /* 相關網站連結 */
    val attachmentURL: kotlin.String? = null,
    /* 消息公告日期時間 */
    val publishTime: kotlin.String? = null,
    /* 開始時間 */
    val startTime: kotlin.String? = null,
    /* 結束時間 */
    val endTime: kotlin.String? = null,
    /* 消息更新時間 */
    val updateTime: kotlin.String? = null
) {

    /**
    * 消息類別
    * Values: _1colon,_2colon,_3colon,_4colon,_5colon,_6colon,_7colon,_8colonAPI,_9colon,_99colon
    */
    enum class NewsCategory(val value: kotlin.String){
    
        @Json(name = "1: 最新消息") _1colon("1: 最新消息"),
    
        @Json(name = "2: 新聞稿") _2colon("2: 新聞稿"),
    
        @Json(name = "3: 營運資訊") _3colon("3: 營運資訊"),
    
        @Json(name = "4: 轉乘資訊") _4colon("4: 轉乘資訊"),
    
        @Json(name = "5: 活動訊息") _5colon("5: 活動訊息"),
    
        @Json(name = "6: 系統公告") _6colon("6: 系統公告"),
    
        @Json(name = "7: 新服務上架") _7colon("7: 新服務上架"),
    
        @Json(name = "8: API修正") _8colonAPI("8: API修正"),
    
        @Json(name = "9: 來源異常") _9colon("9: 來源異常"),
    
        @Json(name = "99: 其他") _99colon("99: 其他");
    
    }

}

