/**
* MOTC Transport  API V2
* </div>   <div class=\"info_description markdown\">本平臺提供涵蓋全國尺度之公車、臺鐵、高鐵、捷運、航空、自行車等公共運輸旅運資料服務API，歡迎各產政學單位介接使用。<br><span class=\"swagger-description-indicatation\">利用本平臺開放資料進行各項應用服務開發時，請考量不同特性使用者(如:性別/殘障/視障/老幼等)的需求，並歡迎回饋寶貴意見。</span><br><br>資料使用葵花寶典:<a href= https://ptxmotc.gitbooks.io/ptx-api-documentation/content/ >請點我</a><br>資料服務開發實作參考手冊:<a href= https://docs.google.com/viewer?url=https://github.com/ptxmotc/PTX_Web/blob/master/Swagger%E6%9C%8D%E5%8B%99%E8%AA%AA%E6%98%8E%E4%B8%8A%E5%82%B3%E5%8F%83%E8%80%83%E6%AA%94%E6%A1%88/%E5%85%AC%E5%85%B1%E9%81%8B%E8%BC%B8%E6%95%B4%E5%90%88%E8%B3%87%E8%A8%8A%E5%B9%B3%E5%8F%B0%E8%B3%87%E6%96%99%E6%9C%8D%E5%8B%99%E9%96%8B%E7%99%BC%E5%AF%A6%E4%BD%9C.pdf?raw=true >請點我</a><br>API URI Convention文件說明:<a href= https://docs.google.com/viewer?url=https://github.com/ptxmotc/PTX_Web/blob/master/Swagger%E6%9C%8D%E5%8B%99%E8%AA%AA%E6%98%8E%E4%B8%8A%E5%82%B3%E5%8F%83%E8%80%83%E6%AA%94%E6%A1%88/API_URI_Convention%E6%96%87%E4%BB%B6_v1.pdf?raw=true >請點我</a>
*
* OpenAPI spec version: v2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.ServiceDTOVersion2AviationCodeShare

/**
 * 航空定期時刻表資料
 * @param airlineID 航空公司IATA國際代碼
 * @param scheduleStartDate 班表開始日期(ISO8601格式:yyyy-MM-dd)
 * @param scheduleEndDate 班表結束日期(ISO8601格式:yyyy-MM-dd)
 * @param flightNumber 班機號碼
 * @param departureAirportID 起點機場IATA國際代碼
 * @param departureTime 起點機場出發時間 (格式: HH:mm 當地時間，跨日以+1 表示)
 * @param codeShare 共用班號
 * @param arrivalAirportID 目的地機場IATA國際代碼
 * @param arrivalTime 終點機場抵達時間 (格式: HH:mm 當地時間，跨日以+1 表示)
 * @param monday 週一飛行與否
 * @param tuesday 週二飛行與否
 * @param wednesday 週三飛行與否
 * @param thursday 週四飛行與否
 * @param friday 週五飛行與否
 * @param saturday 週六飛行與否
 * @param sunday 週日飛行與否
 * @param terminal 航廈
 * @param updateTime 資料更新日期時間(ISO8601格式:yyyy-MM-ddTHH:mm:sszzz)
 */
data class ServiceDTOVersion2AviationGeneralFlightSchedule (
    /* 航空公司IATA國際代碼 */
    val airlineID: kotlin.String,
    /* 班表開始日期(ISO8601格式:yyyy-MM-dd) */
    val scheduleStartDate: kotlin.String,
    /* 班表結束日期(ISO8601格式:yyyy-MM-dd) */
    val scheduleEndDate: kotlin.String,
    /* 班機號碼 */
    val flightNumber: kotlin.String,
    /* 起點機場IATA國際代碼 */
    val departureAirportID: kotlin.String,
    /* 起點機場出發時間 (格式: HH:mm 當地時間，跨日以+1 表示) */
    val departureTime: kotlin.String,
    /* 目的地機場IATA國際代碼 */
    val arrivalAirportID: kotlin.String,
    /* 終點機場抵達時間 (格式: HH:mm 當地時間，跨日以+1 表示) */
    val arrivalTime: kotlin.String,
    /* 週一飛行與否 */
    val monday: kotlin.Boolean,
    /* 週二飛行與否 */
    val tuesday: kotlin.Boolean,
    /* 週三飛行與否 */
    val wednesday: kotlin.Boolean,
    /* 週四飛行與否 */
    val thursday: kotlin.Boolean,
    /* 週五飛行與否 */
    val friday: kotlin.Boolean,
    /* 週六飛行與否 */
    val saturday: kotlin.Boolean,
    /* 週日飛行與否 */
    val sunday: kotlin.Boolean,
    /* 資料更新日期時間(ISO8601格式:yyyy-MM-ddTHH:mm:sszzz) */
    val updateTime: kotlin.String,
    /* 共用班號 */
    val codeShare: kotlin.Array<ServiceDTOVersion2AviationCodeShare>? = null,
    /* 航廈 */
    val terminal: kotlin.String? = null
) {

}

