/**
* MOTC Transport  API V2
* </div>   <div class=\"info_description markdown\">本平臺提供涵蓋全國尺度之公車、臺鐵、高鐵、捷運、航空、自行車等公共運輸旅運資料服務API，歡迎各產政學單位介接使用。<br><span class=\"swagger-description-indicatation\">利用本平臺開放資料進行各項應用服務開發時，請考量不同特性使用者(如:性別/殘障/視障/老幼等)的需求，並歡迎回饋寶貴意見。</span><br><br>資料使用葵花寶典:<a href= https://ptxmotc.gitbooks.io/ptx-api-documentation/content/ >請點我</a><br>資料服務開發實作參考手冊:<a href= https://docs.google.com/viewer?url=https://github.com/ptxmotc/PTX_Web/blob/master/Swagger%E6%9C%8D%E5%8B%99%E8%AA%AA%E6%98%8E%E4%B8%8A%E5%82%B3%E5%8F%83%E8%80%83%E6%AA%94%E6%A1%88/%E5%85%AC%E5%85%B1%E9%81%8B%E8%BC%B8%E6%95%B4%E5%90%88%E8%B3%87%E8%A8%8A%E5%B9%B3%E5%8F%B0%E8%B3%87%E6%96%99%E6%9C%8D%E5%8B%99%E9%96%8B%E7%99%BC%E5%AF%A6%E4%BD%9C.pdf?raw=true >請點我</a><br>API URI Convention文件說明:<a href= https://docs.google.com/viewer?url=https://github.com/ptxmotc/PTX_Web/blob/master/Swagger%E6%9C%8D%E5%8B%99%E8%AA%AA%E6%98%8E%E4%B8%8A%E5%82%B3%E5%8F%83%E8%80%83%E6%AA%94%E6%A1%88/API_URI_Convention%E6%96%87%E4%BB%B6_v1.pdf?raw=true >請點我</a>
*
* OpenAPI spec version: v2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.ServiceDTOVersion2BusBusStageFare

import com.squareup.moshi.Json
/**
 * 路線票價資料
 * @param routeID 機關定義路線代號
 * @param routeName 路線名稱
 * @param operatorID 營運業者代碼
 * @param subRouteID 機關定義附屬路線代碼
 * @param subRouteName 附屬路線名稱
 * @param farePricingType 描述該路線計費方式
 * @param isFreeBus 是否為免費公車
 * @param isForAllSubRoutes 該收費方式是否應用到所有附屬路線
 * @param stageFares 計費站區間計費
 * @param updateTime 本平台資料更新時間(ISO8601格式:yyyy-MM-ddTHH:mm:sszzz)
 */
data class ServiceDTOVersion2BusBusRouteFare (
    /* 機關定義路線代號 */
    val routeID: kotlin.String,
    /* 營運業者代碼 */
    val operatorID: kotlin.String,
    /* 描述該路線計費方式 */
    val farePricingType: ServiceDTOVersion2BusBusRouteFare.FarePricingType,
    /* 是否為免費公車 */
    val isFreeBus: ServiceDTOVersion2BusBusRouteFare.IsFreeBus,
    /* 該收費方式是否應用到所有附屬路線 */
    val isForAllSubRoutes: ServiceDTOVersion2BusBusRouteFare.IsForAllSubRoutes,
    /* 本平台資料更新時間(ISO8601格式:yyyy-MM-ddTHH:mm:sszzz) */
    val updateTime: kotlin.String,
    /* 路線名稱 */
    val routeName: kotlin.String? = null,
    /* 機關定義附屬路線代碼 */
    val subRouteID: kotlin.String? = null,
    /* 附屬路線名稱 */
    val subRouteName: kotlin.String? = null,
    /* 計費站區間計費 */
    val stageFares: kotlin.Array<ServiceDTOVersion2BusBusStageFare>? = null
) {

    /**
    * 描述該路線計費方式
    * Values: _0colon,_1colon,_2colon
    */
    enum class FarePricingType(val value: kotlin.String){
    
        @Json(name = "0: 段次計費") _0colon("0: 段次計費"),
    
        @Json(name = "1: 起迄站間計費") _1colon("1: 起迄站間計費"),
    
        @Json(name = "2: 計費站區間計費") _2colon("2: 計費站區間計費");
    
    }

    /**
    * 是否為免費公車
    * Values: _0colon,_1colon
    */
    enum class IsFreeBus(val value: kotlin.String){
    
        @Json(name = "0: 否") _0colon("0: 否"),
    
        @Json(name = "1: 是") _1colon("1: 是");
    
    }

    /**
    * 該收費方式是否應用到所有附屬路線
    * Values: _0colon,_1colon
    */
    enum class IsForAllSubRoutes(val value: kotlin.String){
    
        @Json(name = "0: 否") _0colon("0: 否"),
    
        @Json(name = "1: 是") _1colon("1: 是");
    
    }

}

