/**
* MOTC Transport  API V2
* </div>   <div class=\"info_description markdown\">本平臺提供涵蓋全國尺度之公車、臺鐵、高鐵、捷運、航空、自行車等公共運輸旅運資料服務API，歡迎各產政學單位介接使用。<br><span class=\"swagger-description-indicatation\">利用本平臺開放資料進行各項應用服務開發時，請考量不同特性使用者(如:性別/殘障/視障/老幼等)的需求，並歡迎回饋寶貴意見。</span><br><br>資料使用葵花寶典:<a href= https://ptxmotc.gitbooks.io/ptx-api-documentation/content/ >請點我</a><br>資料服務開發實作參考手冊:<a href= https://docs.google.com/viewer?url=https://github.com/ptxmotc/PTX_Web/blob/master/Swagger%E6%9C%8D%E5%8B%99%E8%AA%AA%E6%98%8E%E4%B8%8A%E5%82%B3%E5%8F%83%E8%80%83%E6%AA%94%E6%A1%88/%E5%85%AC%E5%85%B1%E9%81%8B%E8%BC%B8%E6%95%B4%E5%90%88%E8%B3%87%E8%A8%8A%E5%B9%B3%E5%8F%B0%E8%B3%87%E6%96%99%E6%9C%8D%E5%8B%99%E9%96%8B%E7%99%BC%E5%AF%A6%E4%BD%9C.pdf?raw=true >請點我</a><br>API URI Convention文件說明:<a href= https://docs.google.com/viewer?url=https://github.com/ptxmotc/PTX_Web/blob/master/Swagger%E6%9C%8D%E5%8B%99%E8%AA%AA%E6%98%8E%E4%B8%8A%E5%82%B3%E5%8F%83%E8%80%83%E6%AA%94%E6%A1%88/API_URI_Convention%E6%96%87%E4%BB%B6_v1.pdf?raw=true >請點我</a>
*
* OpenAPI spec version: v2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.ServiceDTOVersion2ApplicationTourismPicture
import org.openapitools.client.models.ServiceDTOVersion2BasePointType

/**
 * 取得觀光旅宿資料
 * @param ID 旅館民宿代碼
 * @param name 旅館民宿名稱
 * @param description 旅館民宿簡述
 * @param grade 觀光旅館星級
 * @param address 旅館民宿地址
 * @param zipCode 郵遞區號
 * @param phone 旅館民宿電話
 * @param fax 旅館民宿傳真
 * @param websiteUrl 旅館民宿網站網址
 * @param picture 
 * @param position 
 * @param propertyClass 旅館民宿分類
 * @param mapUrl 旅館民宿地點簡圖連結網址
 * @param spec 房型、價目及數量說明
 * @param serviceInfo 服務內容介紹
 * @param parkingInfo 停車資訊
 * @param city 所屬縣市
 * @param srcUpdateTime 觀光局檔案更新時間(ISO8601格式:yyyy-MM-ddTHH:mm:sszzz)
 * @param updateTime 本平台資料更新時間(ISO8601格式:yyyy-MM-ddTHH:mm:sszzz)
 */
data class ServiceDTOVersion2ApplicationHotelTourismInfo (
    /* 旅館民宿代碼 */
    val ID: kotlin.String,
    /* 觀光局檔案更新時間(ISO8601格式:yyyy-MM-ddTHH:mm:sszzz) */
    val srcUpdateTime: kotlin.String,
    /* 本平台資料更新時間(ISO8601格式:yyyy-MM-ddTHH:mm:sszzz) */
    val updateTime: kotlin.String,
    /* 旅館民宿名稱 */
    val name: kotlin.String? = null,
    /* 旅館民宿簡述 */
    val description: kotlin.String? = null,
    /* 觀光旅館星級 */
    val grade: kotlin.String? = null,
    /* 旅館民宿地址 */
    val address: kotlin.String? = null,
    /* 郵遞區號 */
    val zipCode: kotlin.String? = null,
    /* 旅館民宿電話 */
    val phone: kotlin.String? = null,
    /* 旅館民宿傳真 */
    val fax: kotlin.String? = null,
    /* 旅館民宿網站網址 */
    val websiteUrl: kotlin.String? = null,
    val picture: ServiceDTOVersion2ApplicationTourismPicture? = null,
    val position: ServiceDTOVersion2BasePointType? = null,
    /* 旅館民宿分類 */
    val propertyClass: kotlin.String? = null,
    /* 旅館民宿地點簡圖連結網址 */
    val mapUrl: kotlin.String? = null,
    /* 房型、價目及數量說明 */
    val spec: kotlin.String? = null,
    /* 服務內容介紹 */
    val serviceInfo: kotlin.String? = null,
    /* 停車資訊 */
    val parkingInfo: kotlin.String? = null,
    /* 所屬縣市 */
    val city: kotlin.String? = null
) {

}

