/**
* MOTC Transport  API V2
* </div>   <div class=\"info_description markdown\">本平臺提供涵蓋全國尺度之公車、臺鐵、高鐵、捷運、航空、自行車等公共運輸旅運資料服務API，歡迎各產政學單位介接使用。<br><span class=\"swagger-description-indicatation\">利用本平臺開放資料進行各項應用服務開發時，請考量不同特性使用者(如:性別/殘障/視障/老幼等)的需求，並歡迎回饋寶貴意見。</span><br><br>資料使用葵花寶典:<a href= https://ptxmotc.gitbooks.io/ptx-api-documentation/content/ >請點我</a><br>資料服務開發實作參考手冊:<a href= https://docs.google.com/viewer?url=https://github.com/ptxmotc/PTX_Web/blob/master/Swagger%E6%9C%8D%E5%8B%99%E8%AA%AA%E6%98%8E%E4%B8%8A%E5%82%B3%E5%8F%83%E8%80%83%E6%AA%94%E6%A1%88/%E5%85%AC%E5%85%B1%E9%81%8B%E8%BC%B8%E6%95%B4%E5%90%88%E8%B3%87%E8%A8%8A%E5%B9%B3%E5%8F%B0%E8%B3%87%E6%96%99%E6%9C%8D%E5%8B%99%E9%96%8B%E7%99%BC%E5%AF%A6%E4%BD%9C.pdf?raw=true >請點我</a><br>API URI Convention文件說明:<a href= https://docs.google.com/viewer?url=https://github.com/ptxmotc/PTX_Web/blob/master/Swagger%E6%9C%8D%E5%8B%99%E8%AA%AA%E6%98%8E%E4%B8%8A%E5%82%B3%E5%8F%83%E8%80%83%E6%AA%94%E6%A1%88/API_URI_Convention%E6%96%87%E4%BB%B6_v1.pdf?raw=true >請點我</a>
*
* OpenAPI spec version: v2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


/**
 * 路段靜態資訊
 * @param routeID 路段編號(營運業者代碼+路段原編號)
 * @param sourceID 營運業者代碼
 * @param roadSection 路段中文名稱描述
 * @param localtionPath 路段(Link)所屬 Location Path ID
 * @param startLocaltionPoint 路段(Link)起點 Location Point ID
 * @param endLocaltionPoint 路段(Link)迄點 Location Point ID
 * @param roadType 道路等級(1.國道、2.快速公路(如西濱快速公路等)、 3.省道、4.快速道路(如建國高架橋等)、5.市區道路、 6.縣道、7.其它)
 * @param fromkm 起點里程數(表示方式：整數公里數+整數公里數下 3 位，如 36K+525，無里程數則填 WGS84 坐標系統 （X,Y）
 * @param tokm 迄點里程數(表示方式：整數公里數+整數公里數下 3 位，如 36K+525，無里程數則填 WGS84 坐標系統 （X,Y）
 * @param speedLimit 路段速限值，單位：kph。
 * @param srcUpdateTime 來源端平台資料更新時間(ISO8601格式:yyyy-MM-ddTHH:mm:sszzz)
 * @param updateTime 資料更新日期時間(ISO8601格式:yyyy-MM-ddTHH:mm:sszzz)
 */
data class ServiceDTOVersion2RoadRoadInfo (
    /* 路段編號(營運業者代碼+路段原編號) */
    val routeID: kotlin.String,
    /* 營運業者代碼 */
    val sourceID: kotlin.String,
    /* 路段中文名稱描述 */
    val roadSection: kotlin.String? = null,
    /* 路段(Link)所屬 Location Path ID */
    val localtionPath: kotlin.String? = null,
    /* 路段(Link)起點 Location Point ID */
    val startLocaltionPoint: kotlin.String? = null,
    /* 路段(Link)迄點 Location Point ID */
    val endLocaltionPoint: kotlin.String? = null,
    /* 道路等級(1.國道、2.快速公路(如西濱快速公路等)、 3.省道、4.快速道路(如建國高架橋等)、5.市區道路、 6.縣道、7.其它) */
    val roadType: kotlin.String? = null,
    /* 起點里程數(表示方式：整數公里數+整數公里數下 3 位，如 36K+525，無里程數則填 WGS84 坐標系統 （X,Y） */
    val fromkm: kotlin.String? = null,
    /* 迄點里程數(表示方式：整數公里數+整數公里數下 3 位，如 36K+525，無里程數則填 WGS84 坐標系統 （X,Y） */
    val tokm: kotlin.String? = null,
    /* 路段速限值，單位：kph。 */
    val speedLimit: kotlin.String? = null,
    /* 來源端平台資料更新時間(ISO8601格式:yyyy-MM-ddTHH:mm:sszzz) */
    val srcUpdateTime: kotlin.String? = null,
    /* 資料更新日期時間(ISO8601格式:yyyy-MM-ddTHH:mm:sszzz) */
    val updateTime: kotlin.String? = null
) {

}

